# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

- modules:
  - {name: [Data.Set, Data.HashSet], as: S}
  - {name: [Data.HashMap], as: HM}
  - {name: [Data.Map, Data.Map.Strict], as: M}
  - {name: [Data.List], as: L}

# Force NITTA.Utils.Base

- warn: {lhs: "Data.Set.unions (map f l)", rhs: NITTA.Utils.Base.unionsMap x}
- warn: {lhs: "head (Data.Set.elems s)", rhs: NITTA.Utils.Base.oneOf s}

- warn: {lhs: "Data.Text.pack (Data.String.ToString.toString s)", rhs: NITTA.Utils.Base.toText s}
- warn: {lhs: "Data.Text.pack (show s)", rhs: NITTA.Utils.Base.showText s}
- warn: {lhs: "fromString (Data.Text.unpack x)", rhs: fromText x}
- warn: {lhs: "read (Data.Text.unpack t)", rhs: NITTA.Utils.Base.readText t}

# Ignore:

- ignore: { name: "Avoid lambda" }
- ignore: { name: "Eta reduce" }
- ignore: { name: "Use tuple-section" }
- ignore: { name: "Use zipWith" }

- ignore: { within: "NITTA.Intermediate.Simulation.Tests", name: "Fuse mapM_/map" }
- ignore: { within: "NITTA.Intermediate.Value.Tests", name: "Evaluate" }
- ignore: { within: "NITTA.Intermediate.Value.Tests", name: "Use camelCase" }
- ignore: { within: "NITTA.Model.ProcessorUnits.Accum.Tests", name: "Reduce duplication" }
- ignore: { within: "NITTA.Model.ProcessorUnits.Divider.Tests", name: "Reduce duplication" }
- ignore: { within: "NITTA.Model.ProcessorUnits.Fram", name: "Redundant map" }
- ignore: { within: "NITTA.Model.ProcessorUnits.Multiplier.Tests", name: "Reduce duplication" }
- ignore: { within: "NITTA.Model.ProcessorUnits.Tests.DSL", name: "Use uncurry" }
- ignore: { within: "NITTA.Model.ProcessorUnits.Tests.DSL.Tests", name: "Reduce duplication" }
- ignore: { within: "NITTA.Model.Tests.Microarchitecture", name: "Reduce duplication" }
- ignore: { within: "NITTA.Project.Template", name: "Avoid lambda using `infix`" }
- ignore: { within: "NITTA.Tests", name: "Reduce duplication" }
- ignore: { within: "NITTA.Tests", name: "Use uncurry" }
- ignore: { within: "NITTA.UIBackend.ViewHelper", name: "Use <$>" }
- ignore: { within: "NITTA.Utils.Tests", name: "Reduce duplication" }
- ignore: { within: "Spec", name: "Use list comprehension" }
