type = "fx32.32"
ioSync = "Sync"

[[networks]]
name = "net1"

# Array of PUs

[[networks.pus]]
type = "SPI"
name = "spi"
mosi = "mosi"
miso = "miso"
sclk = "sclk"
cs = "cs"
isSlave = true
bufferSize = 6
bounceFilter = 0

# Array of PU prototypes

[[networks.protos]] 
type = "Fram"
name = "fram{x}" # If you want a PU can be allocated only once, remove {x} from the PU name.
size = 32

[[networks.protos]]
type = "Shift"
name = "shift{x}"
sRight = true

[[networks.protos]]
type = "Multiplier"
name = "mul{x}"
mock = true

[[networks.protos]]
type = "Accum"
name = "accum{x}"
isInt = true

[[networks.protos]]
type = "Divider"
name = "div{x}"
mock = true
pipeline = 4