name: Haskell Sanity

on:
  pull_request:

jobs:

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v1
      with:
        version: '3.1.6'

    - name: 'Run HLint'
      uses: haskell/actions/hlint-run@v1
      with:
        path: .
        fail-on: warning

  fourmolu:
    runs-on: ubuntu-latest
    steps:
      - name: Cache haskell-stack and fourmolu
        uses: actions/cache@v2.1.3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-haskell-stack-${{ hashFiles('**/stack.yaml', '**/package.yaml') }}-fourmolu

      - name: Install haskell-stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true

      - name: Install fourmolu
        run: |
          stack install fourmolu
          echo ~/.local/bin >> $GITHUB_PATH

      - uses: actions/checkout@v2
      - name: Check formatting
        run: find . -name '*.hs' | xargs fourmolu -m check
